language: c

sudo: false

matrix:
  include:
    - env: LUA="lua 5.1"
      os: osx
    - env: LUA="lua 5.1"
      os: linux
    - env: LUA="lua 5.2"
      os: linux
    - env: LUA="lua 5.3"
      os: linux
    - env: LUA="luajit 2.0"
      os: linux
    - env: LUA="luajit 2.1"
      os: linux

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks make rockspecs/environ-scm-0.rockspec

before_script:
  - luarocks install luacheck
  - luarocks install lunitx

script:
  - cd test
  - lunit.sh test.lua
  - luacheck ../src/lua

notifications:
  email:
    on_success: change
    on_failure: always
