language: c

sudo: false

# matrix:
#   include:
#     - compiler: ": Lua51osx"
#       env: LUA="lua 5.1"
#       os: osx
#     - compiler: ": Lua51"
#       env: LUA="lua 5.1"
#       os: linux
#     - compiler: ": Lua52"
#       env: LUA="lua 5.2"
#       os: linux
#     - compiler: ": Lua53"
#       env: LUA="lua 5.3"
#       os: linux
#     - compiler: ": LuaJIT20"
#       env: LUA="luajit 2.0"
#       os: linux
#     - compiler: ": LuaJIT21"
#       env: LUA="luajit 2.1"
#       os: linux

matrix:
  include:
    - compiler: gcc
      env: LUA="lua 5.1"
      os: osx
    - compiler: clang
      env: LUA="lua 5.1"
      os: osx
    - compiler: gcc
      env: LUA="lua 5.1"
      os: linux
    - compiler: gcc
      env: LUA="lua 5.2"
      os: linux
    - compiler: gcc
      env: LUA="lua 5.3"
      os: linux
    - compiler: gcc
      env: LUA="luajit 2.0"
      os: linux
    - compiler: gcc
      env: LUA="luajit 2.1"
      os: linux

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks make rockspecs/environ-scm-0.rockspec

before_script:
  - luarocks show luacheck > /dev/null 2>&1 || luarocks install luacheck
  - luarocks show lunitx > /dev/null 2>&1   || luarocks install lunitx

script:
  - cd test
  - lunit.sh test.lua
  - luacheck ../src/lua

before_cache:
  - luarocks remove environ

notifications:
  email:
    on_success: change
    on_failure: always
