version: 0.1.0.{build}

environment:
  matrix:
  - LUA: "lua 5.1"
  - LUA: "lua 5.2"
  - LUA: "lua 5.3"

platform:
  - x64
  - x86

before_build:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - if /I "%platform%"=="x86" set HR_TARGET=vs_32
  - if /I "%platform%"=="x64" set HR_TARGET=vs_64
  - hererocks env --%LUA% --target %HR_TARGET% -rlatest
  - call env\bin\activate

build_script:
  - luarocks make rockspecs\environ-scm-0.rockspec

before_test:
  - luarocks show winreg || luarocks install winreg
  - luarocks show lunitx || luarocks install lunitx
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls

test_script:
  - cd test
  - lua test.lua
